baseURL                = "https://kursatbal.com/"
locale                 = "en-us"
title                  = "Kürşat Bal"
defaultContentLanguage = "en"
hasCJKLanguage         = false
enableRobotsTXT        = true

[pagination]
    pagerSize = 12

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[taxonomies]
    category = "categories"
    tag      = "tags"

[outputs]
    home = ["HTML", "RSS"]
