[[main]]
    identifier = "projects"
    name       = "Projeler"
    url        = "/categories/"
    weight     = -80

    [main.params]
        icon = "categories"



[[main]]
    identifier = "posts"
    name       = "Yazılar"
    url        = "/categories/yazılar/"
    weight     = -85

    [main.params]
        icon = "messages"
